module.exports = {
	primary: "#ff5778",
	secondary: "#ff9500",
	background: "#EEF0F3",
	"background-raised": "#E6E9EC",
	"background-raised-hover": "#E3E5E7",
	surface: "#F8F9FA",
	"surface-hover": "#F3F4F7",
	"surface-selected": "#EEEFF1",
	"surface-selected-hover": "#E9EAEC",
	"surface-inset": "#F0F1F1",
	"surface-bright": "#FFFFFF",
	border: "#DADFE7",
	card: "#F7F8F8",
}
